### ISSUE TITLE
Piwik logo is sometimes not visible

### ISSUE THREAD

**Issue by loomchild** [puffinrocks/puffin#11]
It's due to ad-blockers - apparently they don't like name Piwik.

**Comment by loomchild** [comment]
There isn't much I can do about it right now.

**Comment by joubertredrat** [comment]
This is because you're using adblock

**Comment by loomchild** [comment]
Yeah, I noticed:) 

In fact the issue is fixed now on master since a few weeks - when fetching the image I am prefixing "piwik" application name (BTW, now called Motomo:) with a string "media-", and it seems to trick the adblockers.
