### ISSUE TITLE
unable to recursively clone repo as per the readme

### ISSUE THREAD

**Issue by rocketman0** [puffinrocks/puffin#13]
Sorry if I'm missing something obvious but I'm unable to clone the repo recursively

```
m@minty ~ $ git clone --recursive git@github.com:puffinrocks/puffin.git
Cloning into 'puffin'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by rocketman0** [comment]
manually changed all the references I could find to git@github.com:puffinrocks into https://github.com/puffinrocks and it now seems to be working

**Comment by rocketman0** [comment]
Tried on macOS and didn't encounter this error, it is possible that the issue could be isolated to Linux. My other systems are running Linux Mint 18.1 Serena

**Comment by rocketman0** [comment]
Realised I didn't have my ssh key from my linux machines on my github account which is why I couldn't clone the repo, now that I've added it seems to be working as expected. Might not be a bad idea to note this on readme page though

**Comment by loomchild** [comment]
Hi,

Thanks for info. I had similar issues when integrating with Travis CI. I am planning to avoid submodule entirely and replace it with dynamic app repos in the future, so probably no point to improve the README at the moment.

Cheers,
Jarek
