### ISSUE TITLE
Puffin Blog 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by Jeeppler** [puffinrocks/puffin#22]
while trying to visit [`http://blog.puffin.rocks/`](http://blog.puffin.rocks/) I got this error message `503 Service Temporarily Unavailable`

**Comment by loomchild** [comment]
Yeah, it's down since a while. I removed a link to it as well. I will probably use mastodon, twitter or something similar, since there's not much articles / traffic anyway.

Thanks for noticing.
