### ISSUE TITLE
Demo Site is down

### ISSUE THREAD

**Issue by worldworm** [puffinrocks/puffin#27]
your demo page is not available.

If the URL has changed, please open a pull request at 
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

https://github.com/Kickball/awesome-selfhosted/issues/1767

**Comment by loomchild** [comment]
Hi,

Thanks for contacting me.

Yes, I have shut down the demo server as the project is unfortunately not actively maintained anymore as marked in README.

Best regards,
Jarek Lipski

**Comment by loomchild** [comment]
I can create a PR for awesome-selfhosted if you wish, but I am not sure how to write it. The code is still there and some people might be using it, but I simply don't plan add any new features to it at the moment and don't want to maintain the demo server.

**Comment by worldworm** [comment]
Thanks for your quick response. I've changed it :)
Ive just removed the site, so this project remains in the list.
