### ISSUE TITLE
How about Puffin Web Browser.rpm/.deb ?

### ISSUE THREAD

**Issue by 1457384613gh** [puffinrocks/puffin#28]
How about Puffin Web Browser.rpm/.deb ?
Would Puffin Web Browser be coming for Linux ?
Chrome done, Edge doing, Puffin should catch the linux users
to improve the market competitiveness.

**Comment by loomchild** [comment]
I am afraid you are contacting the wrong people - this project has nothing to do with Puffin web browser.
