### ISSUE TITLE
CSRF token missing

### ISSUE THREAD

**Issue by bigdoods** [puffinrocks/puffin#4]
Hello,

I have installed the latest puffin and when I try to register or login I get the following error:
``` CSRF token missing ```

Could it be to do with using my server IP address for the env variables SERVER_NAME & VIRTUAL_HOST?

Any other ideas why?

**Comment by loomchild** [comment]
Do you have SECRET_KEY defined as described in the doc?

**Comment by bigdoods** [comment]
Yes, it is set.

**Comment by loomchild** [comment]
I will take a look into it later. Could you share the result of the following command:

    docker logs puffin_main_1

**Comment by bigdoods** [comment]
No container exists with that name.

**Comment by loomchild** [comment]
Then try:

    docker logs puffin_puffin_1

(it depends how your main service is called in your docker-compose.yml)

**Comment by bigdoods** [comment]
http://35.187.38.228/

logs for puffin_puffin_1 seem fine:

``` 
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
User puffin already exists
serving on http://0.0.0.0:8080
```

I think it has a problem with the IP in the compose file
![screenshot from 2017-03-15 18-54-52](https://cloud.githubusercontent.com/assets/3436953/23965799/1bd7f5aa-09b1-11e7-98e4-ee2b3a9ba0b8.png)
 
I will try run it with a domain address instead and report back.

**Comment by bigdoods** [comment]
Issue fixed by by updating SERVER_NAME and VIRTUAL_HOST values to an actual dns.

http://beta.jenca.io

**Comment by loomchild** [comment]
Makes sense.
