### ISSUE TITLE
Is it possible to add Parse Server with Parse Dashboard?

### ISSUE THREAD

**Issue by serhii-londar** [puffinrocks/puffin#8]
Is it possible to add [Parse Server](http://parseplatform.org) with [Parse Dashboard](https://github.com/parse-community/parse-dashboard)?

**Comment by serhii-londar** [comment]
Is it possible to add [Parse Server](http://parseplatform.org) with [Parse Dashboard](https://github.com/parse-community/parse-dashboard)?

**Comment by loomchild** [comment]
Hi,

Sure it would be possible. Could you tell me in more what does Parse do?

Also please feel free to try to add it yourself - I can offer your help and some basic infos and you can use existing apps as examples. I would be very interested to see if the docs are sufficiently clear for new contributors. If you don't feel like, let me know, I should be able to find some time in coming weeks.

**Comment by loomchild** [comment]
Hi, 

I read a bit about Parse, I understand it's a place to deploy simple back-ends for mobile applications. It seems nice, but I won't be using it at the moment. 

Would you interested in adding it? Is everyone else interested in using it?

I found out it's already [dockerized](https://github.com/parse-community/parse-server#inside-a-docker-container), but I don't know what are other requirements and what amount of memory it needs.

**Comment by loomchild** [comment]
Hi, 

I read a bit about Parse, I understand it's a place to deploy simple back-ends for mobile applications. It seems nice, but I won't be using it at the moment. 

Would you interested in adding it? Is everyone else interested in using it?

I found out it's already [dockerized](https://github.com/parse-community/parse-server#inside-a-docker-container), but I don't know what are other requirements and what amount of memory it needs.
