### ISSUE TITLE
Replacing Puffin front end

### ISSUE THREAD

**Issue by bigdoods** [puffinrocks/puffin#9]
Hi Jarek,

I am currently trying to replace the front end of Puffin so that the frontend and backend are decoupled. The first task that I have set myself is that a user must login prior to accessing the catalogue.

I have made a basic login page and I am using Ajax to send requests to the server. However, I am running into some issues with Cross Origin Resource Sharing (CORS). From research, I suspect that because my login page is not submitting a compatible CSRF token to the server, thus, the server is rejecting my Ajax request to login with "CSRF token missing" (See [this stackoverflow answer](https://stackoverflow.com/a/21501593) for reasons that this happens).

I have tried reading the CSRF token from browser API using ```var csrftoken = Cookies.get('csrftoken')``` and then submitting it as a part of the header request to the server ``` $.ajax { ... headers:{"HTTP_X_CSRF_TOKEN":csrftoken}, ...  }```

I assume that the CSRF need to match and are generated as a part of the templates in puffin and forwarded as a header in the HTML in the puffin frontend? Do you have any suggestions to get around this? 

Thank you!

**Comment by loomchild** [comment]
I don't quite see the relation between CORS and CSRF, to me they are completely separate. I think you can disable CSRF in Flask pretty easily, and dealing with CORS requires setting up correct headers and/or properly configuring domains. 

In general your plan of replacing a front-end sounds like a serious change that the current code is not really adapted for (sort of a completely new project), so I won't be able to help. I was also planning to separate the Puffin into command-line utility and user interface, but currently I don't have time to do it.
